### ISSUE TITLE
Charts not working for Laravel

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#12]
The charts on the Dashboard does not currently work for Laravel apps.

**Comment by arnaudbesnier** [comment]
Hey Herman,

We are finalizing the new version of the Laravel liana. We'll release this version this week.
The charts will be fully supported with this version.

We appreciate your patience.

**Comment by arnaudbesnier** [comment]
The new version (0.0.2) has been merged on master!
As soon as the version 0.0.2 is available on [Packagist](https://packagist.org/packages/forestadmin/forest-laravel), you can update the version using this command:

`composer update forestadmin/forest-laravel`

As the package has been simplified, you should read the new README file to make sure that the updated package is properly configured.

I close the issue, don't hesitate to reopen it if necessary.
