### ISSUE TITLE
Stripe, Intercom, etc. Integrations not available for Laravel

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#13]
No way of integrating with Stripe, Intercom and other 3rd party services at the moment. This is possible with the other platforms (Rails, Express).

**Comment by arnaudbesnier** [comment]
Hey Herman,

This is definitely something we will implement in the next iteration.
Stripe and Intercom will be the first 3rd party services supported by the Forest Laravel liana.

**Comment by hermanschutte** [comment]
@arnaudbesnier @SeyZ Any update on this? It's been outstanding for a very long time now.

**Comment by arnaudbesnier** [comment]
@hermanschutte which integrations you need? We need your use cases/specifications to understand if it is generic enough to start the implementation of these integrations.

**Comment by hermanschutte** [comment]
@arnaudbesnier We need Stripe and Intercom. This was promised by @SeyZ last year when we paid to fund the development of Forest. It seems Laravel development has now been put on the back burner and no real progress is being made.

@SeyZ Please comment.

**Comment by valentinfily** [comment]
Stripe integration for Laravel much needed too

**Comment by arnaudbesnier** [comment]
Hi @valentinfily, can you provide the use cases you have to help us implement the Stripe integration.

**Comment by egyptik** [comment]
Is this still not available in Laravel?

**Comment by arnaudbesnier** [comment]
Hi @hermanschutte, @valentinfily, @egyptik,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
