### ISSUE TITLE
Filters - Charts filtered on associations are not working

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#17]
When adding a filter to a chart that depends on a relationship a SQLSTATE[42S22] error is generated.

**Comment by arnaudbesnier** [comment]
hey @hermanschutte, 

I would be happy to fix this.
It seems that the generated query is not valid. Can you provide some details about the type of chart you're trying to create? Maybe a screenshot of the chart configuration in Forest would be a good start.

Thanks!

**Comment by hermanschutte** [comment]
Hi @arnaudbesnier,

Here is a screenshot of the configuration:
![Uploading Screen Shot 2016-11-21 at 10.43.36 AM.png…](Chart Configuration)

I get the following SQL error: 

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'widget:id' in 'where clause' (SQL: select count(*) as aggregate from `user_widgets` where `widget:id` > 18)```

**Comment by arnaudbesnier** [comment]
Thanks a lot, the associations filters on chart are not supported yet on Laravel. This is something we will just release for the other stacks (Rails, Express). Be sure that the next version will include the feature.

**Comment by hermanschutte** [comment]
I'm confused. Are you saying it will not be released for Laravel?

**Comment by arnaudbesnier** [comment]
Sorry for the confusion, we will obviously support this type of chart in the future.

**Comment by arnaudbesnier** [comment]
Sorry for the confusion, we will obviously support this type of filters for charts in the future.

**Comment by arnaudbesnier** [comment]
hey @hermanschutte, here is the "one-to-one" association support for filters on charts: https://github.com/ForestAdmin/forest-laravel/pull/21
