### ISSUE TITLE
First entry in a totally new table yeilds strange insert dates...

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#2]
Row #1 inserted a few minutes before the next one, check the last two fields on each:

``` php
1   
Exactitude  
Given on correct answers    
TRUE    
fa fa-check-square color-green  
\App\Achievements\Analyzers\ExactitudeAnalyzer  
03/10/2016 03:24:40 
03/10/2016 03:24:40
```

``` php
2   
Different   
Given for correct answers that are not the exact answer 
TRUE    
fa fa-exclamation-triangle color-orange 
\App\Achievements\Analyzers\DifferentAnalyzer   
02/10/2016 19:38:27 
02/10/2016 19:38:27
```

**Comment by crazycodr** [comment]
More on this, all further entries store dates correctly, only the first one is totally off

**Comment by arnaudbesnier** [comment]
Hi @crazycodr,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
