### ISSUE TITLE
Tinyint colum is reported as a checkbox

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#3]
My Badge table has a tinyint 4 column, it yields a checkbox control in forest admin which is invalid. Right now i only have 2 states so it is ok, but later on, i will need more than 2 states.

**Comment by arnaudbesnier** [comment]
Hi @crazycodr,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
