### ISSUE TITLE
After upgrading to Laravel 5.4 Class auth.forest does not exist

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#30]
After upgrading to Laravel 5.4, we now get the following error for all models:

```
ReflectionException in Container.php line 681:
Class auth.forest does not exist
```

**Comment by arnaudbesnier** [comment]
Hi @hermanschutte , the fix is available in the new package version 0.0.17.
Thanks for the feedback!

🌲 🌲 🌲

**Comment by hermanschutte** [comment]
@arnaudbesnier thanks. Is this available via Composer yet?

**Comment by arnaudbesnier** [comment]
@hermanschutte yes it is:
https://packagist.org/packages/forestadmin/forest-laravel
