### ISSUE TITLE
Paging doesn't work as expected

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#4]
I have more than 10 elements in my table but i see only 1 page. Changing page works and page number changes too, but i always have 1 page icon which is the current page, not the expected pagination.

**Comment by arnaudbesnier** [comment]
Hey Mathieu,

We are working on a new version of the Laravel liana.
We re-implemented it from scratch and the pagination will be working properly.
We will release this new version this week.

Hope you'll enjoy it!

**Comment by arnaudbesnier** [comment]
The new version (0.0.2) has been merged on master!

As soon as the version 0.0.2 is available on Packagist, you can update the version using this command:
composer update forestadmin/forest-laravel

As the package has been simplified, you should read the new README file to make sure that the updated package is properly configured.

I close the issue, don't hesitate to reopen it if necessary.
