### ISSUE TITLE
belongsTo with foreign key not named 'id'

### ISSUE THREAD

**Issue by sfriquet** [ForestAdmin/forest-laravel#42]
I have a model who has a belongsTo relationship with a model whose primary key is not called 'id' and I believe this is what's preventing it from loading.

'id' is harcoded here https://github.com/ForestAdmin/forest-laravel/blob/devel/src/Http/Services/ResourcesGetter.php#L76 and I guess that's the issue.

**Comment by arnaudbesnier** [comment]
Hey @sfriquet, thanks for the report!
The liana is still pretty young, I'll try to fix this issue for our next week sprint.

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
Fix released in the latest liana version 0.1.3.

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
Hi @sfriquet,

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
