### ISSUE TITLE
missing forest.url

### ISSUE THREAD

**Issue by matteoerrera** [ForestAdmin/forest-laravel#43]
By installing Forest from Composer, the 'url' key is not generated in the file /config/forest.php, and from the dashboard the 'collection' selectbox is empty.

By adding
`    'url' => 'https://forestadmin-server.herokuapp.com',
`

all work.

**Comment by arnaudbesnier** [comment]
Hi @matteoerrera, thanks for the feedback.
That is really weird. You are the first to have this kind of issue.

The `url` is supposed to be set by default, see the following line: https://github.com/ForestAdmin/forest-laravel/blob/9a7df61f2eeba7fd306b883be7a17c2544502f83/config/forest.php#L4
Can you detail a bit what you did to install Forest? Did you follow the onboarding steps?

Having a dashboard with the `collection` selectbox empty is a consequence of the first issue I guess.

**Comment by arnaudbesnier** [comment]
@matteoerrera do you still have your issue?

**Comment by matteoerrera** [comment]
I think it was my mistake, with a recent update I no longer have this problem. Thank you!
