### ISSUE TITLE
Forest 🌳🌳🌳 Cannot find the models directory

### ISSUE THREAD

**Issue by MartinRdw** [ForestAdmin/forest-laravel#62]
## Expected behavior

Can not change model directory.

## Failure Logs

Forest 🌳🌳🌳 Cannot find the models directory

## Context

During the Forest installation I have set a bad model path "app/models" instead of "app", I have change to "app" in my forest.php config file and resend with php artisan forest:send-apimap.

I have the same error in my Laravel logs and on my forest dashboard at https://app.forestadmin.com/xxx/dashboard/xxx I have a wheel that turns indefinitely.

* Package Version: "forestadmin/forest-laravel": "^0.2.0"
* Laravel Version: 5.5.36

**Comment by ArnaudValensi** [comment]
Hi @MartinRdw, Laravel may use the cache for configuration. You can run `php artisan config:cache` to recreate the cache from the new configuration.

**Comment by arnaudbesnier** [comment]
Hi @MartinRdw ,

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
