### ISSUE TITLE
Can't configure project

### ISSUE THREAD

**Issue by matteoerrera** [ForestAdmin/forest-laravel#64]
## Expected behavior

After the successful installation wizard, the expected behaviour is to see the forest admin dashboard.

## Actual behavior

The dashboard stops on loading, and shows the message:

> "Your project is being configured.
> This page will be reloaded automatically when the operation is completed. "
> endlessly

## Failure Logs

On Javascript console there is one error:
`Uncaught (in promise) 
Object
message
:
"The message port closed before a response was received."
__proto__
:
Object`

## Context

* Package Version: 0.2.0
* Laravel Version: v5.5.34

**Comment by arnaudbesnier** [comment]
Hey @matteoerrera, are you sure that you have models or collections on the project you setup Forest? On our side, It looks like no models have been detected by Forest.

**Comment by arnaudbesnier** [comment]
Hi @matteoerrera,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
