### ISSUE TITLE
[*] PHP Version - Forest does not support PHP 7.2

### ISSUE THREAD

**Issue by egyptik** [ForestAdmin/forest-laravel#65]
## Expected behavior

Trying to run `php artisan forest:send-apimap` or trying to sign in through the Forest app on a fresh install should just work.

## Actual behavior

All API calls being made by the `forest-laravel` package fail with:

`count(): Parameter must be an array or an object that implements Countable`

Is PHP 7.2 supported at all? See https://wiki.php.net/rfc/counting_non_countables

## Context

* **PHP Version: 7.2**
* Package Version: 0.2.0
* Laravel Version: 5.5.22
* Database Dialect: MySQL
* Database Version: 5.7.20

**Comment by arnaudbesnier** [comment]
Hey @egyptik, thanks for the feedback.
I am pretty sure that Forest has not been tested on a project running with PHP 7.2.
Then it must be a global issue with PHP 7.2 support.

**Comment by egyptik** [comment]
Thanks @arnaudbesnier! Just to confirm: switched to 7.1 and `php artisan forest:send-apimap` is working.

Only now I'm getting CORS erros with the Google authentication on the Forest dashboard.. 🤔

**Comment by egyptik** [comment]
Fixed! :)

**Comment by bjorntheart** [comment]
I had no issue running the command with PHP 7.2. I'm running a Laravel Homestead vagrant instance. 


**php -v**
```
PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.18.2~linux-x64-non_zts72, https://blackfire.io, by SensioLabs
```

**Comment by arnaudbesnier** [comment]
Hi @egyptik,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
