### ISSUE TITLE
[-] Documention - Missing documentation for Laravel

### ISSUE THREAD

**Issue by bjorntheart** [ForestAdmin/forest-laravel#67]
Hey, guys.

Any chance of adding Laravel documentation soon? Even just a sample Laravel project would help.
I just cannot figure out to start populating my Forest Admin dashboard. 

Any guidance would be welcome.

**Comment by bjorntheart** [comment]
Ok, finally got my domain logic synced with my admin section.

I didn't notice this artisan command at first:

```bash
php artisan forest:send-apimap
```

**Comment by tyteck** [comment]
Hi sorry to disturb here but ... where did you select the stack (laravel)
In the doc I see **Choose your stack (Laravel)**
On http://app.forestadmin.com/XXXXX/install the only choices I see are
Postgres, mysql, sql server, mongodb
Ruby, Express/sequelize, Express Moongoose

I've configured everything, php artisan forest:send-apimap is running but I don't see any laravel choice.
Is it my eyes ?

**Comment by arnaudbesnier** [comment]
Hi @tyteck this repository is not officially maintained anymore. As a consequence, it is not an option in Forest Admin onboarding.

You should use Lumber to generate an admin API microservice on top of your database.
See the following documentation: https://docs.forestadmin.com/documentation/getting-started/installation/install-with-lumber

**Comment by arnaudbesnier** [comment]
Hi @bjorntheart, @tyteck,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
