### ISSUE TITLE
Hidden attribute values are sent and shown in the admin

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#7]
The point of an hidden attribute is that it should never be returned to the API, you can only update it or provide a special means to check it. Best example is the password field in a user's table. Default code for laravel:

``` php


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden
        = [
            'password',
            'remember_token',
        ];
```

The password and remember token should NEVER be shown in ForestAdmin but i should be able to update it if i provide a value.

**Comment by arnaudbesnier** [comment]
Thanks Mathieu for the report.

This is definitely something we will consider in the next iteration.

**Comment by arnaudbesnier** [comment]
Hi @crazycodr,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
