### ISSUE TITLE
missing forest.collection 

### ISSUE THREAD

**Issue by kingluffyxx** [ForestAdmin/forest-laravel#71]
in SearchBuilder.php ligne 25
`$config = Config::get('forest.collection');`

$config => null

so the following code in ligne 27

`if (array_key_exists($collectionName, $config)) {`

return a error

`ErrorException
array_key_exists() expects parameter 2 to be array, null given`

* Package Version: 0.4.0
* Laravel Version: 5.4.36

**Comment by arnaudbesnier** [comment]
Hi @kingluffyxx, thanks for the feedback, this should be fixed on the devel branch now.
The fix will be release in a few minutes in the version 0.5.0.

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
Hi @kingluffyxx,

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
