### ISSUE TITLE
Forest admin get

### ISSUE THREAD

**Issue by semal-vora** [ForestAdmin/forest-laravel#74]
## Expected behavior

TODO: Please describe here the behavior you are expecting.
While run command `composer require forestadmin/forest-laravel` it should change composer jason file with forest admin codes. 

## Actual behavior

TODO: What is the current behavior?
Getting confliction between forest admin and laravel framework. 
In conclusion it shows 1:- "**Remove laravel/framework v5.2.45**" 
2:- "**Don't install laravel/framework v5.2.45**"
3:- "forestadmin/forest-laravel 0.5.1 requires barryvdh/laravel-cors ^0.11.0 -> satisfiable by barryvdh/laravel-cors[v0.11.0, v0.11.1, v0.11.2]."

## Failure Logs

TODO: Please include any relevant log snippets, if necessary.

## Context

TODO: Please provide any relevant information about your setup.

* Package Version: 
* Laravel Version: 5.2
* Database Dialect:
* Database Version:

**Comment by arnaudbesnier** [comment]
Hi @semal-vora,

This issue will be closed as the repository will be archived soon.

The brand new Laravel agent for Forest Admin is available here:
https://github.com/ForestAdmin/laravel-forestadmin

As we now have a team of dedicated developers for this new Laravel agent, be sure Forest Admin will provide a much better Laravel support experience compared to the one you had in the past for v1.

Forest Admin also evolved a lot in 4 years as an internal tool platform, don’t hesitate to give it another try, you should not be disappointed 🌲🌲🌲 

Best Regards.
