### ISSUE TITLE
Relationship view is useless if you can't link stuff correctly

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#8]
I have tons of rows in table A and i have a relationship to table B in my detailed view of table A but i can't create a new row for table B from there taking the id from table A as a context.

Even worst, if i try to create a row in table B, i have a field "table_a_id" in that form but i have no way to find the right ID to put in there. Not very useful!

**Comment by arnaudbesnier** [comment]
Hey Mathieu,

the global issue you described will be fixed in the new Laravel Liana.

**Comment by arnaudbesnier** [comment]
The new version (0.0.2) has been merged on master!

As soon as the version 0.0.2 is available on Packagist, you can update the version using this command:
composer update forestadmin/forest-laravel

As the package has been simplified, you should read the new README file to make sure that the updated package is properly configured.

I close the issue, don't hesitate to reopen it if necessary.
