### ISSUE TITLE
Relationship view not returned data correctly

### ISSUE THREAD

**Issue by crazycodr** [ForestAdmin/forest-laravel#9]
I have two tables A and B. A hasMany B and B belongsTo A. I have records in both tables and there is a B with the correct ID towards A in my database.

When i visit the relationship view B in record details A, i cannot see the B records associated with it. Don't know why, it could be a bug or me that didn't configure the relationships fine, i will know later, i have to input data for now to test it right!

**Comment by arnaudbesnier** [comment]
Hey Mathieu,

This is a bug of the first version of the liana. Be sure that will be fixed in the new version.

**Comment by arnaudbesnier** [comment]
The new version (0.0.2) has been merged on master!

As soon as the version 0.0.2 is available on Packagist, you can update the version using this command:
composer update forestadmin/forest-laravel

As the package has been simplified, you should read the new README file to make sure that the updated package is properly configured.

I close the issue, don't hesitate to reopen it if necessary.
